// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using motitask;

#nullable disable

namespace motitask.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20240525194131_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.19");

            modelBuilder.Entity("motitask.Alternative", b =>
                {
                    b.Property<int>("A_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("A_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("A_id");

                    b.ToTable("Alternatives");
                });
#pragma warning restore 612, 618
        }
    }
}
